runtime: python27
threadsafe: true
api_version: 1
basic_scaling:
  max_instances: 2

builtins:
- appstats: on

#[START_EXCLUDE]
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?setuptools/script \(dev\).tmpl$
#[END_EXCLUDE]

handlers:
# The endpoints handler must be mapped to /_ah/api.
- url: /_ah/api/.*
  script: api.API
  secure: always

libraries:
- name: pycrypto
  version: latest
- name: ssl
  version: latest


# [START env_vars]
env_variables:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy swagger.json' command.
  ENDPOINTS_SERVICE_NAME: caas-prototype.appspot.com
  ENDPOINTS_SERVICE_VERSION: 2018-11-21r0
 # [END env_vars]
